name: Build and publish package to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Building new package version and publishing to PyPI
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.2.2
      - name: Check Poetry version
        run: poetry --version
      - name: Install dynamic versioning plugin
        run: poetry self add poetry-dynamic-versioning==0.22.0
      - name: Build package
        run: poetry build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
